[[projects]]
src = "$img/InclusiveMicro.png"
alt = "Image description 1"
quickDesc = "Quick description of Project 1"
longDesc = """Long description of Project 1. 
You can add more details here over multiple lines."""
projectTitle = "Project Title 1"

[[projects]]
src = "$img/InclusiveMicro.png"
alt = "Image description 2"
quickDesc = "Quick description of Project 2"
longDesc = """Long description of Project 2. 
This description can also span multiple lines for more detail."""
projectTitle = "Project Title 2"

[[projects]]
src = "$img/InclusiveMicro.pngg"
alt = "Image description 3"
quickDesc = "Quick description of Project 3"
longDesc = """Long description of Project 3. 
Include as much detail as you like over several lines."""
projectTitle = "Project Title 3"
